# Generated by Django 5.2.6 on 2025-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('university', models.CharField(max_length=255, verbose_name='Университет')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('course', models.CharField(max_length=50, verbose_name='Курс обучения')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название модуля/темы')),
                ('description', models.TextField(verbose_name='Описание блока обучения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Модуль программы',
                'verbose_name_plural': 'Модули программы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('photo', models.ImageField(help_text='Желательно квадратное изображение', upload_to='speakers/', verbose_name='Фотография')),
                ('position', models.CharField(max_length=300, verbose_name='Должность, опыт')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
                'ordering': ['id'],
            },
        ),
    ]
