# Generated by Django 5.2.6 on 2025-09-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_background', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фон для главного блока')),
                ('section_background', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фон для светлых секций')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
