# Generated by Django 5.2.6 on 2025-09-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_widget_code',
            field=models.TextField(blank=True, help_text='Вставьте сюда HTML-код виджета с Яндекс.Карт', null=True, verbose_name='Код виджета карты (HTML)'),
        ),
    ]
