# Generated by Django 5.2.6 on 2025-09-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_map_widget_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='map_widget_code',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_latitude',
            field=models.FloatField(blank=True, help_text='Например: 59.969240', null=True, verbose_name='Широта центра карты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_longitude',
            field=models.FloatField(blank=True, help_text='Например: 30.316317', null=True, verbose_name='Долгота центра карты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=16, help_text='Значение от 1 до 19. Оптимально: 16-17.', verbose_name='Масштаб карты'),
        ),
    ]
